# Test your FastAPI endpoints

GET http://127.0.0.1:8700/

###


POST http://127.0.0.1:8700/knowledge/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer myapikey

{
  "collection": "tangshi-4",
  "metadatas": [
    {
      "tag": "network"
    }
  ],
  "texts": [
    "Docker容器运行的时候有host、bridge、none三种网络可供配置。默认是bridge，即桥接网络，以桥接模式连接到宿主机；host是宿主网络，即与宿主机共用网络；none则表示无网络，容器将无法联网。"
  ]
}

###

POST http://127.0.0.1:8700/knowledge/search
Accept: application/json
Content-Type: application/json
Authorization: Bearer myapikey

{
  "collection": "tangshi-4",
  "query": "多令，同柳阜之、刘去非、石民瞻、周嘉仲、陈孟参、孟容"
}

###

POST http://127.0.0.1:8700/knowledge/search
Accept: application/json
Content-Type: application/json
Authorization: Bearer myapikey

{
  "collection": "tangshi-4",
  "query": "主机"
}

###

POST http://127.0.0.1:8700/knowledge/search
Accept: application/json
Content-Type: application/json
Authorization: Bearer myapikey

{
  "collection": "mikrotik_library",
  "query": "IP"
}

###

POST http://127.0.0.1:8700/token/stat
Accept: application/json
Content-Type: application/json
Authorization: Bearer myapikey

{
  "text": "多令，同柳阜之、刘去非、石民瞻、周嘉仲、陈孟参、孟容"
}
